name: srwnn_mobile
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  image_picker:
  image:
  tflite_flutter: ^0.5.0
  tflite_flutter_helper: ^0.1.2
  photo_view: ^0.10.2
  path_provider: ^1.6.14
  cupertino_icons: ^0.1.3
  gallery_saver: ^2.0.1
  flutter_spinkit: ^4.1.2
  url_launcher: ^5.5.2
  dio: ^3.0.10
  firebase_admob: ^0.9.3
  flutter_launcher_icons: ^0.7.5

dev_dependencies:
  flutter_launcher_icons: "^0.7.3"
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"

flutter:
  uses-material-design: true
  assets:
    #- assets/images/test.jpg
    - assets/models/srwnn.tflite
    - assets/models/
    - assets/images/test.png
    - assets/images/modelExamples/
    - assets/lang/en.json
    - assets/lang/es.json
