name: srwnn_mobile
description: A new Flutter project.

version: 2.0.1+7

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  image_picker: ^0.6.7+22
  image: ^2.1.19
  tflite_flutter: ^0.5.0
  tflite_flutter_helper: ^0.1.2
  photo_view: ^0.10.3
  path_provider: ^1.6.27
  cupertino_icons: ^0.1.3
  gallery_saver: ^2.0.3
  flutter_spinkit: ^4.1.2
  url_launcher: ^5.7.10
  dio: ^3.0.10
  firebase_admob: ^0.11.0+1
  flutter_launcher_icons: ^0.7.5
  #blobs: ^1.2.0
  carousel_slider: ^2.3.1
  provider: ^4.3.2+2
  firebase_auth: ^0.20.0+1
  cloud_firestore: ^0.16.0
  firebase_core: ^0.7.0
  firebase_storage: ^7.0.0
  flutter_signin_button: ^1.1.0
  google_sign_in: ^4.5.9

dev_dependencies:
  #flutter_launcher_icons: "^0.7.3"
  flutter_test:
    sdk: flutter

# Será necesario quitar esta wea cuando flutter localization y firebase auth sean compatibles
#dependency_overrides:
  #intl: ^0.17.0-nullsafety.2

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"

flutter:
  uses-material-design: true
  assets:
    #- assets/images/test.jpg
    - assets/
    - assets/models/srwnn.tflite
    - assets/models/
    - assets/images/test.png
    - assets/images/modelExamples/
    - assets/lang/en.json
    - assets/lang/es.json
